/*Exercise 1: From dbo.FactInternetSales and dbo.DimSalesTerritory, Write a query displaying the sales orders where the sales amount exceeds $1,000.  

Retrieve only those rows have the territory region is Canada. */ 

-- Your code here  

Select top 50 Fis.SalesAmount, 

DST.SalesTerritoryRegion 

---,DST.SalesAmount 

From dbo.FactInternetSales as FIS 

INNER JOIN dbo.DimSalesTerritory as DST  

On FIS.SalesTerritoryKey=DST.SalesTerritoryKey 

Where FIS.SalesAmount > 1000 and DST.SalesTerritoryRegion like '%canada%' 

 

--- Bài làm đúng 

 

/*Exercise 2:  

From dbo.DimProduct and dbo.DimProductSubcategory,   

Write a query displaying the Product key,   EnglishProductName, and Color columns which has EnglishProductSubCategoryName is 'Mountain Bikes'.  

And  interger part of ListPrice = 3399 */  

Select  

DP.ProductKey 

,Dp.ListPrice 

,DP.EnglishProductName 

,DP.Color 

,DPS.EnglishProductSubcategoryName 

From dbo.DimProduct as DP  

JOIN dbo.DimProductSubcategory as DPS on DP.ProductSubcategoryKey=DPS.ProductSubcategoryKey 

Where DPS.EnglishProductSubcategoryName like '%Mountain bike%' 

and FLOOR(DP.ListPrice)=3399 

 

 

---Bài làm đúng 

 



-- Your code here    

/*Exercise 3: From dbo.DimPromotion, dbo.FactInternetSales 

Write a query display ProductKey, SalesOrderNumber, SalesAmount from rows which has discount percentage >= 20% */ 

-- Your code here    

---Chữa bài 

Select  

FIS.ProductKey, 

FIS.SalesOrderNumber, 

FIS.SalesAmount, 

DP.DiscountPct, 

Format(dp.DiscountPct,'p') as pct  

from dbo.FactInternetSales as FIS 

left join dbo.DimPromotion AS DP on FIS.promotionkey=dp.promotionkey 

Where DiscountPct >= 0.2 

 

/*Exercise 4: From dbo.DimCustomer, dbo.DimGeography,  

Display Phone number of customer who has yearly income > 150000 and come from United States */ 

-- Your code here    

SELECT  

DC.Phone 

,DC.YearlyIncome 

,DG.EnglishCountryRegionName 

From dbo.DimCustomer as DC  

Join dbo.DimGeography as DG on DC.GeographyKey=DG.GeographyKey 

Where DC.YearlyIncome > 150000 

and DG.EnglishCountryRegionName like '%United States%' 

 ---Bài làm đúng 

 

-- Logical expression   

/* Exercise 5: From dbo.DimProduct,    

Get ProductKey, EnglishProductName and 2 new columns:      

a. ProductFlag is generated by the string preceded by the '-' character in EnglishProductName.    

(If EnglishProductName do not have '-' then keep EnglishProductName value.) 

b. GroupSize follows by conditions:      

- Size is 'S' or less than 43 --> 'small'     

- Size is 'M' or 'L' or from 43 to 57 --> 'medium'     

- Size is 'XL' or larger than 57 --> 'big'     

- NULL --> 'no size' */   

-- Your code here    

SELECT ProductKey 

, EnglishProductName 

, Right(EnglishProductName,len(EnglishProductName)-CHARINDEX('-',EnglishProductName)) as ProductFlag 

,Case 

WHEN TRY_CONVERT(int,SIZE) > 57 THEN 'big' 

WHEN TRY_CONVERT(int,SIZE) > 43 THEN 'medium' 

WHEN SIZE IS NULL Then 'no size' 

ELSE 'small' 

END as GroupSize 

From dbo.DimProduct 

 

---Bài làm chưa đúng , bạn cần dùng LEFT thay vì RIGHT , và câu lệnh case when còn chưa đủ điều kiện 

---Bài chữa 

SELECT ProductKey 

, EnglishProductName 

, Left(EnglishProductName,len(EnglishProductName)-CHARINDEX('-',EnglishProductName)) as ProductFlag 

, size 

, Case 

WHEN TRY_CONVERT(int,SIZE) > 57 OR size = 'XL' THEN 'big' 

WHEN TRY_CONVERT(int,SIZE) > 43 or size in ('m','L') THEN 'medium' 

WHEN SIZE IS NULL Then 'no size' 

ELSE 'small' 

END as GroupSize 

From dbo.DimProduct 

 

 

-- UNION concept 

/* Exercise 6: From dbo.From DimCustomer, dbo.ProspectiveBuyer 

Display list Customer/Buyer FullName (combine FirstName, MiddleName, LastName), Gender, EmailAddress then caculate Age of Customer/Buyer now (using BirthDate). */ 

-- Your code here  

select  

CONCAT_WS(' ',FirstName,MiddleName,LastName) as FullName, 

Gender, 

EmailAddress, 

Datediff(Year,BirthDate,Getdate()) as AGE 

from dbo.DimCustomer 

UNION 

select  

CONCAT_WS(' ',FirstName,MiddleName,LastName) as FullName, 

Gender, 

EmailAddress, 

Datediff(Year,BirthDate,Getdate()) as AGE 

from dbo.ProspectiveBuyer 

 

---Bài làm đúng 